point_backbone:
  size_input: 5
  input_features: ["intensity", "xyz", "radius"]
  nb_channels: 768
  nb_class: 1024 # nb_class should match the size of the vit features
  depth: 48
  dim_proj: [2, 1, 0]
  grid_shape: [[256, 256], [256, 32], [256, 32]]
  fov: [[-64, -64, -8], [64, 64, 8]]
  num_neighbors: 16
  voxel_size: 0.1
  max_points: 20000
  layernorm: True

image_backbone:
  images_encoder: "dinov2_vit_large_p14"
  feat: "x_pre_norm"
  im_size: [224, 448]
 
dataloader:
  batch_size: 8
  num_workers: 128
  num_epochs: 25

optim:
  lr: 0.002
  weight_decay: 0.03
  iter_warmup: 3500
  min_lr: 0.00001
